packages:
  - "playground"

overrides:
  "@nuxt/schema": "4.4.8"
  "@nuxtjs/harlem": "link:./"

strictPeerDependencies: false

shamefullyHoist: true

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  unrs-resolver: false
