packages:
  - "playground"

overrides:
  "@nuxt/schema": "4.6.0"
  "@nuxtjs/harlem": "workspace:*"

strictPeerDependencies: false

shamefullyHoist: true

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  unrs-resolver: false
